services:
  app:
    image: sangao:1.0
    build:
      context: .
      pull: false        # ğŸ‘ˆ å…³é”®ï¼ç¦æ­¢æ„å»ºæ—¶æ‹‰å–æˆ–æ£€æŸ¥åŸºç¡€é•œåƒ    
    volumes:
      - ./:/projects/sangao/
      - /var/run/docker.sock:/var/run/docker.sock  # å…³é”®æŒ‚è½½
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true  # æˆäºˆç‰¹æƒ      
    ports:
      - "80:80"
    restart: unless-stopped

